# Generated by Django 3.2.2 on 2021-05-12 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('code', models.CharField(max_length=5)),
                ('currency_code', models.CharField(max_length=6)),
                ('times_looked', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IpRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, unique=True)),
                ('distance_to_uy', models.FloatField(default=0)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_country', to='tracer.country')),
            ],
        ),
    ]
