version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./dockervolumes/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./dockervolumes/redis:/data

  web:
    build:
      context: .
    env_file:
      - env_docker
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
