version: "3.9"

volumes:
  pg-data:

services:
  postgres:
    image: postgres
    container_name: trafilea_db
    volumes:
      - pg-data:/pg-data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - pg-data:/pg-data

  web:
    build:
      context: .
    env_file:
      - env_docker
    volumes:
      - pg-data:/pg-data
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
